#!/usr/bin/python -u
# Copyright (c) 2019 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Run LCRP Daemon
"""
from pylcrp import lcrpd

if __name__ == "__main__":
    lcrpd.main()
